name: Bug Report/Feature request
description: File a bug report or a feature request
body:
  - type: markdown
    attributes:
      value: |
        Use this form if you think you want a change to BBT.

        Alongside a description of your problem/question/feature suggestion, please also include a debug log ID.

        You can generate a debug log ID by:
        1. reproducing the problem
        2. selecting the problematic reference(s)
        3. right-clicking them
        4. choose `BBT debug log` from the popup menu.

        If the regular debug log submission does not work, use "send to file.io" from the help menu.

        If you are sure your question does not relate to items in your library at all, just select any one item in your library.
  - type: input
    id: debug-log
    attributes:
      label: Debug log ID
      description: Please fill in an actual debug log ID here. Logs that look like `D<number>` are Zotero logs, `@retorquere` has no access to those. Better BibTeX Debug logs will end in `-euc` or `-apse`, and if you are sending item samples, there will be `-refs-` in the ID.
      placeholder: ex. ABCD1234-ref-euc or nNwplUbkYrQu-ABCD1234 for file.io.
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: What happened?
      description: and what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## DO NOT just write "N/A" for the debug log ID.

        It is usually false, and if you think it's nonetheless true, provide an explanation. If you just can't imagine what it is useful for, simply submit one. When you omit it, the issue bot will chime in explaining how to generate a debug log ID. Please read that message attentively.
